name: 'Setup .NET Core Action'
description: 'Downloads and sets up a specific version of .NET Core'
inputs:
  version:
    description: '.NET Core version to install (e.g., 3.1)'
    required: false
    default: '3.1.0'
outputs:
  dotnet-path:
    description: 'Path to .NET executable'
runs:
  using: 'composite'
  steps:

    - uses: actions/checkout@v3
    
    - name: Download .NET Core
      shell: bash
      run: |
        wget https://download.visualstudio.microsoft.com/download/pr/76cabfc3-6010-472e-a5b3-bfe854a24c4e/1810de5554f8cd9825b47ae46b9990b4/dotnet-runtime-3.1.0-rhel.6-x64.tar.gz
        mkdir -p ${{ github.workspace }}/dotnet
        tar zxf dotnet-runtime-${{ inputs.version }}-rhel.6-x64.tar.gz -C ${{ github.workspace }}/dotnet
        pwd
        ls
        cd dotnet 
        ls
        
      env:
        DOTNET_VERSION: ${{ inputs.version }}
    - name: Output .NET Version
      shell: bash
      run: ${{ github.workspace }}/dotnet --version
