name: 'Setup .NET Core Action'
description: 'Downloads and sets up a specific version of .NET Core'
inputs:
  version:
    description: '.NET Core version to install (e.g., 3.1)'
    required: false
    default: '3.1'
outputs:
  dotnet-path:
    description: 'Path to .NET executable'
runs:
  using: 'composite'
  steps:
    - name: Download .NET Core
      shell: bash
      run: |
        wget https://download.visualstudio.microsoft.com/download/pr/[unique-id]/[file-name].tar.gz
        mkdir -p ${{ github.workspace }}/dotnet
        tar zxf [file-name].tar.gz -C $${{ github.workspace }}/dotnet
      env:
        DOTNET_VERSION: ${{ inputs.version }}
    - name: Output .NET Version
      shell: bash
      run: ${{ github.workspace }}/dotnet/dotnet --version
