name: Setup .NET Core Workflow (Self Hosted)

on:
  workflow_dispatch:
    inputs:
      dotnetVersion:
        description: '.NET Core Version'
        required: true
        default: 3.1.0

jobs:
  setup-dotnet:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: ./.github/actions/setup-dotnecore
      with:
        version: ${{ github.event.inputs.dotnetVersion }}
        
    - name: Display the .env file
      shell: bash
      run: |
        echo "cat .env"
        cat /home/ec2-user/actions-runner/.env
      
    - name: Print current user
      run: whoami

    - name: List files
      shell: bash
      run: |
        pwd
        ls

    - name: echo Workspace
      shell: bash
      run: |
        echo "GITHUB_WORKSPACE=${GITHUB_WORKSPACE}"
        
    - name: echo Cleanup Script
      shell: bash
      run: |
        echo "cat /home/ec2-user/actions-runner/opt/runner/cleanup.sh"
        cat /home/ec2-user/actions-runner/opt/runner/cleanup.sh
          
        
  parallel-job-2:
    runs-on: ubuntu-latest
    steps:
    - name: List files in the current directory
      run: ls -alrt
  
    - name: Echo a text
      run: echo "Hello from workflow"




