name: Setup .NET Core Workflow w/ TypeScrpit Action

on:
  workflow_dispatch:
    inputs:
      dotnetVersion:
        description: '.NET Core Version'
        required: true
        default: 3.1.0

jobs:
  setup-dotnet-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: ./.github/actions/setup-dotnetcore-js
      with:
        version: ${{ github.event.inputs.dotnetVersion }}
    - name: Step-3
      run: ls -alrt
  
    - name: Step-4
      run: echo "Hello from workflow"
    - name: Step-5
      run: whoami
      
  second-parallel-job:
    runs-on: ubuntu-latest
    steps:
    - name: Step-1
      run: ls -alrt
  
    - name: Step-2
      run: echo "Hello from workflow"




